#!/usr/bin/env python
import os.path
import sys
sys.path.append(os.path.abspath(os.path.dirname(os.path.dirname(__file__))))
import src.command_line_tool.command_line_tool as command_line_tool

command_line_tool.command_line_tool("sdb", sys.argv[1:])
