#!/usr/bin/env python
#
# sim_db Command Line Tool

import os.path
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import sim_db.src_command_line_tool.command_line_tool as command_line_tool

command_line_tool.command_line_tool("sdb", sys.argv[1:])
