#!/usr/bin/env python
#
# sim_db Command Line Tool

import os.path
import sys
sys.path.append(os.path.abspath(os.path.dirname(os.path.dirname(__file__))))
import sim_db.src_command_line_tool.command_line_tool as command_line_tool

command_line_tool.command_line_tool("sim_db", sys.argv[1:])
